version: '3'

services:
  mimron-movieapi:
    build: .
    image: mimron-movieapi
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/db-imron
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/mimron-movieapi
    networks:
      - node-network

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network
  
  redis:
    image: redis:latest
    ports:
      - '6379:6379'

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
